import type { Metadata } from "next";
import "@/styles/globals.css";
import ReactQueryProviders from "./providers/ReactQueryProviders";

export const metadata: Metadata = {
  title: "ASTU Schedule Allocator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProviders>{children}</ReactQueryProviders>
      </body>
    </html>
  );
}
